"""Safe skills exposed to the Agent Framework agent."""

from __future__ import annotations

from typing import Annotated, Any

from agent_framework import tool
from pydantic import Field

from microharness.context import ContextManager
from microharness.lifecycle import HOOKS
from microharness.memory import (
    append_tool_trace,
    read_facts,
    remember_fact,
    write_agent_artifact,
)
from microharness.subagents import SUBAGENTS


@tool
def read_harness_context() -> dict[str, str]:
    """Read the controlled local context used by the harness."""

    HOOKS.before_tool("read_harness_context", {})
    context = ContextManager().build()
    result = {"source": context.source, "content": context.knowledge}
    append_tool_trace("read_harness_context", {"source": context.source})
    HOOKS.after_tool("read_harness_context", {"source": context.source})
    return result


@tool
def save_agent_artifact(
    prompt: Annotated[
        str,
        Field(description="Original user prompt that produced the artifact."),
    ],
    summary: Annotated[
        str,
        Field(description="Final concise response generated by the agent."),
    ],
) -> dict[str, Any]:
    """Save the agent response as a reusable markdown artifact and session state."""

    HOOKS.before_tool("save_agent_artifact", {"prompt_chars": len(prompt)})
    state = write_agent_artifact(prompt=prompt, summary=summary)
    append_tool_trace("save_agent_artifact", {"artifact_path": state["artifact_path"]})
    HOOKS.after_tool("save_agent_artifact", {"artifact_path": state["artifact_path"]})
    return {
        "artifact_path": state["artifact_path"],
        "session_state_path": "working/output/session_state.json",
        "run_count": state["run_count"],
        "last_run_at": state["last_run_at"],
    }


@tool
def explain_agent_framework_concept(
    concept: Annotated[
        str,
        Field(
            description=(
                "Concept to explain: loop, tools, context, session, approvals, "
                "MCP, memory, planning or Foundry."
            )
        ),
    ],
) -> dict[str, str]:
    """Explain a core Microsoft Agent Framework concept."""

    key = concept.strip().lower()
    concepts = {
        "loop": (
            "Agent Loop: observe the user message, decide whether a tool is needed, "
            "execute it, incorporate the result and continue until the answer is ready."
        ),
        "tools": (
            "Tools: typed Python functions decorated with @tool. The model chooses "
            "when to call them and receives their result as context."
        ),
        "context": (
            "Context: the prompt, current user turn, tool outputs and relevant state "
            "provided to the model for the next decision."
        ),
        "session": (
            "Session: conversation continuity. The same thread keeps prior turns and "
            "lets the agent behave coherently across requests."
        ),
        "approvals": (
            "Approvals: human-in-the-loop gates for risky tools. AG-UI can surface "
            "approval requests before execution."
        ),
        "mcp": (
            "MCP: a path to connect external tools and data sources without "
            "hardwiring every integration into the app."
        ),
        "memory": (
            "Memory: durable or scoped state that can be added later so the agent "
            "remembers facts beyond one request."
        ),
        "planning": (
            "Planning: a layer above the loop that decomposes goals, chooses steps "
            "and checks progress before acting."
        ),
        "foundry": (
            "Foundry: the production path for model hosting, observability, "
            "evaluations, deployments and enterprise governance."
        ),
    }
    return {
        "concept": key,
        "explanation": concepts.get(
            key,
            "Concepto no reconocido. Prueba con loop, tools, context, session, "
            "approvals, MCP, memory, planning o Foundry.",
        ),
    }


@tool
def remember_session_fact(
    session_id: Annotated[
        str,
        Field(description="Session identifier, for example 'web-session'."),
    ],
    fact: Annotated[
        str,
        Field(description="Short fact to keep in persisted session context."),
    ],
) -> dict[str, Any]:
    """Store a short fact in persisted session context."""

    normalized_session = session_id.strip() or "default"
    normalized_fact = fact.strip()
    HOOKS.before_tool(
        "remember_session_fact",
        {"session_id": normalized_session, "fact_chars": len(normalized_fact)},
    )
    remember_fact(normalized_session, normalized_fact)
    facts = read_facts(normalized_session)
    append_tool_trace("remember_session_fact", {"session_id": normalized_session})
    HOOKS.after_tool(
        "remember_session_fact",
        {"session_id": normalized_session, "facts_in_session": len(facts)},
    )
    return {
        "session_id": normalized_session,
        "stored_fact": normalized_fact,
        "facts_in_session": len(facts),
        "scope": "file-backed-session",
    }


@tool
def read_session_context(
    session_id: Annotated[str, Field(description="Session identifier to inspect.")],
) -> dict[str, Any]:
    """Read the persisted context collected for a session."""

    normalized_session = session_id.strip() or "default"
    return {
        "session_id": normalized_session,
        "facts": read_facts(normalized_session),
        "scope": "file-backed-session",
    }


@tool
def build_context_snapshot(
    session_id: Annotated[str, Field(description="Session identifier for the context snapshot.")],
) -> dict[str, Any]:
    """Return the exact context bundle assembled by the context manager."""

    context = ContextManager().build(session_id)
    return {
        "session_id": context.session_id,
        "source": context.source,
        "facts": context.facts,
        "run_count": context.run_count,
        "prompt_block": context.as_prompt_block(),
    }


@tool
def draft_extension_plan(
    scenario: Annotated[
        str,
        Field(description="Advanced scenario to extend the micro harness toward."),
    ],
) -> dict[str, Any]:
    """Draft next steps to evolve the harness toward advanced agentic scenarios."""

    return {
        "scenario": scenario,
        "steps": [
            "Define the policy boundary: what the agent may decide and what needs "
            "user confirmation.",
            "Add durable session storage for conversation and tool traces.",
            "Introduce the new capability behind a small adapter, not inside the model prompt.",
            "Expose progress and decisions through AG-UI streaming events.",
            "Add evaluation prompts and smoke tests before moving to Foundry deployment.",
        ],
    }


@tool
def delegate_to_subagent(
    name: Annotated[
        str,
        Field(description="Specialist name: architect, reliability or security."),
    ],
    task: Annotated[str, Field(description="Task to delegate to the specialist sub-agent.")],
) -> dict[str, str]:
    """Delegate a bounded task to a deterministic specialist sub-agent."""

    HOOKS.before_tool("delegate_to_subagent", {"name": name})
    result = SUBAGENTS.run(name, task)
    payload = {"name": result.name, "focus": result.focus, "result": result.result}
    append_tool_trace("delegate_to_subagent", payload)
    HOOKS.after_tool("delegate_to_subagent", {"name": result.name, "focus": result.focus})
    return payload


@tool(approval_mode="always_require")
def propose_foundry_deployment(
    environment: Annotated[
        str,
        Field(description="Target environment name, for example dev, test or prod."),
    ],
    reason: Annotated[
        str,
        Field(description="Why this deployment should be approved."),
    ],
) -> dict[str, str]:
    """Propose a deployment action that requires human-in-the-loop approval."""

    return {
        "environment": environment,
        "status": "deployment-proposal-recorded",
        "reason": reason,
        "note": "This safe tool records intent only; it does not deploy anything.",
    }


HARNESS_TOOLS = [
    read_harness_context,
    save_agent_artifact,
    explain_agent_framework_concept,
    remember_session_fact,
    read_session_context,
    build_context_snapshot,
    draft_extension_plan,
    delegate_to_subagent,
    propose_foundry_deployment,
]
